config/routes.rb
Rails.application.routes.draw do
   devise_for :admins, :controllers => {
    :sessions => "admins/sessions",
    :passwords => 'admins/passwords',
    :confirmations => 'admins/confirmations'
  }

  authenticate :admin do
    namespace :admins do
      resources :admins
      resources :profile, :only => [:edit, :update]
      resources :users
      get '/dashboard' => 'dashboards#index', as: :dashboard
      get '/' => 'dashboards#index'
      root 'dashboards#index'
    end
  end


  match 'ping'         => 'tools#ping',           as: :ping, via: :all
  root 'pages#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_admin!
  layout 'admins/default'
  before_filter :check_admin_active
  private
  def check_admin_active
    unless current_admin.active
      flash[:notice]= t(:admin_not_active)
      sign_out current_admin
      redirect_to new_admin_session_path
    end
  end
end

app/controllers/admins/dashboards_controller.rb
class Admins::DashboardsController < AdminController
end

app/controllers/admins/passwords_controller.rb
class Admins::PasswordsController < Devise::PasswordsController
  layout 'admins/default'
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  layout 'admins/default'
  private
  def after_sign_in_path_for(resource)
    admins_dashboard_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/pages_controller.rb
class PagesController < PublicController
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/views/admins/dashboards/index.haml
-content_for(:title){ 'Home' }
-content_for(:page_title){ 'Home' }


.bootstrap-admin-panel-content.bootstrap-admin-no-table-panel-content.collapse.in
  .col-md-3
    - r = rand(100)
    .easyPieChart{"data-percent" => "#{r}", :style => "width: 110px; height: 110px; line-height: 110px;"}
      #{r}%
      %canvas{:height => "110", :width => "110"}
    .chart-bottom-heading
      %span.label.label-info Visitors
  .col-md-3
    - r = rand(100)
    .easyPieChart{"data-percent" => "#{r}", :style => "width: 110px; height: 110px; line-height: 110px;"}
      #{r}%
      %canvas{:height => "110", :width => "110"}
    .chart-bottom-heading
      %span.label.label-info Page Views
  .col-md-3
    - r = rand(100)
    .easyPieChart{"data-percent" => "#{r}", :style => "width: 110px; height: 110px; line-height: 110px;"}
      #{r}%
      %canvas{:height => "110", :width => "110"}
    .chart-bottom-heading
      %span.label.label-info Users
  .col-md-3
    - r = rand(100)
    .easyPieChart{"data-percent" => "#{r}", :style => "width: 110px; height: 110px; line-height: 110px;"}
      #{r}%
      %canvas{:height => "110", :width => "110"}
    .chart-bottom-heading
      %span.label.label-info Orders

app/views/layouts/admins/default.haml
!!!
%html
  %head
    %title
      - unless yield(:title).to_s.empty?
        = yield (:title)
        |
      = 'Art Gallery'
      |
      = 'Tag Line'
    %meta{:content => "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "/assets/css/bootstrap.min.css", :media => "screen", :rel => "stylesheet"}/
    %link{:href => "/assets/css/bootstrap-theme.min.css", :media => "screen", :rel => "stylesheet"}/
    %link{:href => "/assets/css/bootstrap-admin-theme.css", :media => "screen", :rel => "stylesheet"}/
    %link{:href => "/assets/css/bootstrap-admin-theme-change-size.css", :media => "screen", :rel => "stylesheet"}/
    %link{:href => "/assets/css/DT_bootstrap.css", :media => "screen", :rel => "stylesheet"}/

    %link{:href => "/assets/vendors/easypiechart/jquery.easy-pie-chart.css", :media => "screen", :rel => "stylesheet"}/
    %link{:href => "/assets/vendors/easypiechart/jquery.easy-pie-chart_custom.css", :media => "screen", :rel => "stylesheet"}/
    /[if lt IE 9]
      <script type="text/javascript" src="/assets/js/html5shiv.js"></script>
      <script type="text/javascript" src="/assets/js/respond.min.js"></script>
  %body.bootstrap-admin-with-small-navbar
    %nav.navbar.navbar-default.navbar-fixed-top.bootstrap-admin-navbar.bootstrap-admin-navbar-under-small{:role => "navigation"}
      .container
        .row
          .col-lg-12
            .navbar-header
              %button.navbar-toggle{"data-target" => ".main-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
                %span.sr-only Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              = link_to 'Art Gallery Admin Panel', admins_root_path, class: 'navbar-brand'
            - if current_admin
              .collapse.navbar-collapse.main-navbar-collapse
                %ul.nav.navbar-nav
                  %li.active
                    = link_to 'Home', admins_root_path
                  %li
                    %a{:href => "#"} Categories
                  %li
                    %a{:href => "#"} Artists
                  %li
                    %a{:href => "#"} Art
                  %li
                    %a{:href => "#"} Orders
                  %li
                    %a{:href => "#"} Users
                  %li
                    %a{:href => "#"} Admins
    .container
      .row
        .col-md-12
          .row
            .col-lg-12
              .page-header
                %h1= yield (:page_title) if yield (:page_title)
          .row
            .col-lg-12
              .panel.panel-default
                = yield
    / footer
    .navbar.navbar-footer
      .container
        .row
          .col-lg-12
            %footer{:role => "contentinfo"}
              %p.left Art Gallery
              %p.right
                \© 2013 - #{Date.today.strftime('%Y')}
                = link_to 'Art Gallery', admins_root_path, taget: '_blank'
    %script{:src => "http://code.jquery.com/jquery-2.0.3.min.js", :type => "text/javascript"}
    %script{:src => "/assets/js/bootstrap.min.js", :type => "text/javascript"}
    %script{:src => "/assets/js/twitter-bootstrap-hover-dropdown.min.js", :type => "text/javascript"}
    %script{:src => "/assets/js/bootstrap-admin-theme-change-size.js", :type => "text/javascript"}
    %script{:src => "/assets/vendors/datatables/js/jquery.dataTables.min.js", :type => "text/javascript"}
    %script{:src => "/assets/js/DT_bootstrap.js", :type => "text/javascript"}
    %script{:src => "/assets/vendors/easypiechart/jquery.easy-pie-chart.js", :type => "text/javascript"}
:javascript
  $(function() {
      // Easy pie charts
      $('.easyPieChart').easyPieChart({animate: 1000});
  });  

app/views/layouts/application.haml
!!!
%html
  %head
    %title
      - unless yield(:title).to_s.empty?
        = yield (:title)
        |
      = 'Art Gallery'
      |
      = 'Tag Line'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield